export const size = [
  {
    material_type: "canvas_size",
    id: 2931,
    title: "手机海报",
    material: { unit: "px", name: "手机海报", width: "1242", height: "2208" },
  },
  {
    material_type: "canvas_size",
    id: 2932,
    title: "公众号首图 ",
    material: { unit: "px", name: "公众号首图 ", width: "900", height: "383" },
  },
  {
    material_type: "canvas_size",
    id: 2933,
    title: "公众号次图",
    material: { unit: "px", name: "公众号次图", width: "500", height: "500" },
  },
  {
    material_type: "canvas_size",
    id: 12425,
    title: "小红书配图",
    material: { unit: "px", name: "小红书配图", width: "1242", height: "1660" },
  },
  {
    material_type: "canvas_size",
    id: 2934,
    title: "商品主图",
    material: { unit: "px", name: "商品主图", width: "800", height: "800" },
  },
  {
    material_type: "canvas_size",
    id: 2935,
    title: "小程序封面",
    material: { unit: "px", name: "小程序封面", width: "520", height: "416" },
  },
  {
    material_type: "canvas_size",
    id: 2936,
    title: "电商横版海报",
    material: {
      unit: "px",
      name: "电商横版海报",
      width: "1200",
      height: "675",
    },
  },
  {
    material_type: "canvas_size",
    id: 2937,
    title: "电商竖版海报",
    material: {
      unit: "px",
      name: "电商竖版海报",
      width: "1200",
      height: "1920",
    },
  },
  {
    material_type: "canvas_size",
    id: 2938,
    title: "电商全屏海报",
    material: {
      unit: "px",
      name: "电商全屏海报",
      width: "1920",
      height: "700",
    },
  },
  {
    material_type: "canvas_size",
    id: 2939,
    title: "店招",
    material: { unit: "px", name: "店招", width: "1920", height: "150" },
  },
  {
    material_type: "canvas_size",
    id: 2940,
    title: "手机端店铺首页 ",
    material: {
      unit: "px",
      name: "手机端店铺首页 ",
      width: "750",
      height: "1000",
    },
  },
  {
    material_type: "canvas_size",
    id: 12427,
    title: "横版视频封面",
    material: {
      unit: "px",
      name: "横版视频封面",
      width: "1920",
      height: "1080",
    },
  },
  {
    material_type: "canvas_size",
    id: 12428,
    title: "竖版视频封面",
    material: {
      unit: "px",
      name: "竖版视频封面",
      width: "1080",
      height: "1260",
    },
  },
  {
    material_type: "canvas_size",
    id: 12426,
    title: "竖版直播背景",
    material: {
      unit: "px",
      name: "竖版直播背景",
      width: "1242",
      height: "2690",
    },
  },
  {
    material_type: "canvas_size",
    id: 2941,
    title: "PPT（16:9）",
    material: {
      unit: "px",
      name: "PPT（16:9）",
      width: "1920",
      height: "1080",
    },
  },
  {
    material_type: "canvas_size",
    id: 2942,
    title: "名片",
    material: {
      unit: "mm",
      name: "名片",
      width: "96",
      dpi: "300",
      height: "60",
    },
  },
  {
    material_type: "canvas_size",
    id: 2949,
    title: "张贴海报",
    material: {
      unit: "mm",
      name: "张贴海报",
      width: "426",
      dpi: "300",
      height: "576",
    },
  },
  {
    material_type: "canvas_size",
    id: 2948,
    title: "2m易拉宝",
    material: {
      unit: "cm",
      name: "2m易拉宝",
      width: "80",
      dpi: "150",
      height: "200",
    },
  },
  {
    material_type: "canvas_size",
    id: 2947,
    title: "1.8m展架",
    material: {
      unit: "cm",
      name: "1.8m展架",
      width: "80",
      dpi: "150",
      height: "180",
    },
  },
  {
    material_type: "canvas_size",
    id: 2946,
    title: "优惠券",
    material: {
      unit: "mm",
      name: "优惠券",
      width: "168",
      dpi: "300",
      height: "66",
    },
  },
  {
    material_type: "canvas_size",
    id: 2945,
    title: "门票",
    material: {
      unit: "mm",
      name: "门票",
      width: "206",
      dpi: "300",
      height: "86",
    },
  },
  {
    material_type: "canvas_size",
    id: 2944,
    title: "三折页",
    material: {
      unit: "mm",
      name: "三折页",
      width: "291",
      dpi: "300",
      height: "216",
    },
  },
  {
    material_type: "canvas_size",
    id: 2943,
    title: "画册",
    material: {
      unit: "mm",
      name: "画册",
      width: "426",
      dpi: "300",
      height: "291",
    },
  },
  {
    material_type: "canvas_size",
    id: 2950,
    title: "A3纸张",
    material: {
      unit: "mm",
      name: "A3纸张",
      width: "291",
      dpi: "300",
      height: "420",
    },
  },
  {
    material_type: "canvas_size",
    id: 2951,
    title: "A4纸张",
    material: {
      unit: "mm",
      name: "A4纸张",
      width: "210",
      dpi: "300",
      height: "297",
    },
  },
  {
    material_type: "canvas_size",
    id: 2952,
    title: "A5纸张",
    material: {
      unit: "mm",
      name: "A5纸张",
      width: "148",
      dpi: "300",
      height: "210",
    },
  },
];
