export const workareaOption = {
  trigger: "color",
  width: 260,
  height: 641,
  workspaceScale: 1,
  lockScalingX: true,
  lockScalingY: true,
  scaleX: 1,
  scaleY: 1,
  backgroundColor: "#fff",
  hasBorders: false,
  hasControls: false,
  selectable: false,
  lockMovementX: true,
  lockMovementY: true,
  hoverCursor: "default",
  name: "",
  id: "workarea",
  // type: "workarea",
  isElement: false,
};
