export const workareaOption = {
  trigger: "color",
  width: 260,
  height: 641,
  lockScalingX: true,
  lockScalingY: true,
  scaleX: 1,
  scaleY: 1,
  fill: "#fff",
  hasBorders: false,
  hasControls: false,
  selectable: false,
  lockMovementX: true,
  lockMovementY: true,
  hoverCursor: "default",
  name: "",
  id: "workarea",
  unit: "px",
  // type: "workarea",
  isElement: false,
};
export const objectOption = {
  rotation: 0,
  centeredRotation: true,
  strokeUniform: true,
  hoverCursor: "pointer",
  visible: true,
};
export const propertiesToInclude = [
  "id",
  "name",
  "defaultFontFamily",
  "locked",
  "radius",
  "shape",
  "editable",
  "src",
  "expand",
  "type",
  "cloneSrc",
  "background",
  "gradient",
  "materialfield",
  "etype",
  "disabled",
  "bottomColor",
  "selectable",
  "hasBorders",
  "lineWidth",
  "colors",
  "flipX",
  "flipY",
  "fontCustom",
  "scaleX",
  "scaleY",
  "type",
  "left",
  "top",
  "width",
  "height",
  "fill",
  "opacity",
  "visible",
  "fontWeight",
  "fontFamily",
  "fontSize",
  "text",
  "vertical",
  "underline",
  "overline",
  "linethrough",
  "lineHeight",
  "fontStyle",
  "textAlign",
  "charSpacing",
  "id",
  "originX", // 旋转后的素材中心店变了,需要保存
  "originY",
  "name",
  "angle",
  "filters",
  "animation", // 动画
  "maskSvg", // 蒙版svg
  "maskType", // 蒙版类型
  "hasExpire", // 是否过期
  "isExpire", // 是否限时版权素材
  "expireTime", // 到期时间
  "moveX", // 蒙版相关字段
  "initScale", //蒙版缩放后需要记录初始值,否则交互有问题
  "moveY",
  "maskBili",
  "moveScale",
  "bindId",
  "fontName",
  "styles",
  "visibleLeft",
  "visibleTop",
  "multSelect",
];
