export const workareaOption = {
  trigger: "color",
  width: 260,
  height: 641,
  lockScalingX: true,
  lockScalingY: true,
  scaleX: 1,
  scaleY: 1,
  fill: "#fff",
  hasBorders: false,
  hasControls: false,
  selectable: false,
  lockMovementX: true,
  lockMovementY: true,
  hoverCursor: "default",
  name: "",
  id: "workarea",
  unit: "px",
  // type: "workarea",
  isElement: false,
};
export const objectOption = {
  rotation: 0,
  centeredRotation: true,
  strokeUniform: true,
  hoverCursor: "pointer",
  visible: true,
};
export const propertiesToInclude = [
  "id",
  "name",
  "src",
  "backgroundColor",
  "type",
];
